#!/usr/bin/env python3
"""Rebuild the Hoop Trick Shapes gallery data + thumbnails.

Workflow for adding new drawings:
  1. Add the PNG to the spinfinity-adt/hoop-trick-shapes repo, inside the
     trick's folder, named exactly:  Name-Trick-Std-School.png
     (e.g. BarrelRoll/Ananya-BarrelRoll-4th-RGH.png — no extra hyphens)
  2. Commit + push that repo.
  3. Run this script:  python3 build.py
     It pulls the images repo, makes any missing thumbnails in thumbs/,
     and regenerates data.js with the new pinned CDN commit.
  4. Commit + push the website repo.

The script bootstraps its own Pillow install on first run (in ~/.cache),
so plain `python3 build.py` always works.
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMAGES_REPO = "https://github.com/spinfinity-adt/hoop-trick-shapes.git"
CACHE = Path.home() / ".cache" / "hoop-trick-shapes"
CLONE = CACHE / "images"
VENV = CACHE / "venv"
THUMBS = HERE / "thumbs"
DATA_JS = HERE / "data.js"
THUMB_WIDTH = 400
THUMB_QUALITY = 72

TRICK_COLOR = {
    "Barrel Roll": "#0c8294",
    "Cylinder": "#3a66c8",
    "Sphere": "#7a52c4",
    "Waist Hooping": "#bb8b1a",
    "Weave": "#1f9e80",
}
TRICK_SHAPE = {
    "Barrel Roll": "Circle",
    "Cylinder": "Cylinder",
    "Sphere": "Sphere",
    "Waist Hooping": "Chakli",
    "Weave": "Figure-8",
}


def ensure_pillow():
    try:
        import PIL  # noqa: F401
        return
    except ImportError:
        pass
    if sys.prefix == str(VENV):
        sys.exit("Pillow missing even inside the build venv — try deleting %s and rerunning." % VENV)
    py = VENV / "bin" / "python3"
    if not py.exists():
        print("First run: setting up Pillow in", VENV)
        subprocess.run([sys.executable, "-m", "venv", str(VENV)], check=True)
        subprocess.run([str(py), "-m", "pip", "-q", "install", "Pillow"], check=True)
    os.execv(str(py), [str(py)] + sys.argv)


def sync_images_repo() -> str:
    if CLONE.exists():
        subprocess.run(["git", "-C", str(CLONE), "pull", "--ff-only", "-q"], check=True)
    else:
        CLONE.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "clone", "--depth", "1", "-q", IMAGES_REPO, str(CLONE)], check=True)
    head = subprocess.run(["git", "-C", str(CLONE), "rev-parse", "--short", "HEAD"],
                          check=True, capture_output=True, text=True).stdout.strip()
    return head


def spaced(camel: str) -> str:
    return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", camel)


def main():
    ensure_pillow()
    from PIL import Image, ImageOps

    head = sync_images_repo()
    print("images repo @", head)

    pngs = sorted(p for p in CLONE.rglob("*.png") if ".git" not in p.parts)
    THUMBS.mkdir(exist_ok=True)

    entries, made, skipped = [], 0, []
    for i, p in enumerate(pngs, 1):
        parts = p.stem.split("-")
        if len(parts) != 4:
            skipped.append(p.name)
            continue
        name, _, std, school = parts
        trick = spaced(p.parent.name)
        if trick not in TRICK_COLOR:
            skipped.append(p.name)
            continue

        with Image.open(p) as im:
            im = ImageOps.exif_transpose(im)
            w, h = im.size
            thumb_path = THUMBS / (p.stem + ".webp")
            if not thumb_path.exists() or thumb_path.stat().st_mtime < p.stat().st_mtime:
                tw = min(THUMB_WIDTH, w)
                th = max(1, round(h * tw / w))
                im.convert("RGBA" if im.mode in ("RGBA", "LA", "P") else "RGB") \
                  .resize((tw, th), Image.LANCZOS) \
                  .save(thumb_path, "WEBP", quality=THUMB_QUALITY, method=6)
                made += 1

        entries.append({
            "id": i,
            "name": name,
            "trick": trick,
            "std": std,
            "school": school,
            "shape": TRICK_SHAPE[trick],
            "color": TRICK_COLOR[trick],
            "img": f"https://cdn.jsdelivr.net/gh/spinfinity-adt/hoop-trick-shapes@{head}/{p.parent.name}/{p.name}",
            "thumb": f"thumbs/{p.stem}.webp",
            "w": w,
            "h": h,
        })

    # drop thumbnails whose source image was removed from the repo
    valid = {e["thumb"].split("/")[-1] for e in entries}
    stale = [t for t in THUMBS.glob("*.webp") if t.name not in valid]
    for t in stale:
        t.unlink()

    DATA_JS.write_text(
        "// generated by build.py — do not edit by hand\n"
        "const ALL_DATA = " + json.dumps(entries, ensure_ascii=False) + ";\n"
    )
    print(f"{len(entries)} drawings, {made} thumbnail(s) generated, {len(stale)} stale removed -> data.js")
    if skipped:
        print("SKIPPED (bad filename, expected Name-Trick-Std-School.png):")
        for s in skipped:
            print("  ", s)


if __name__ == "__main__":
    main()
